### PR TITLE
Update to `3.35.1`

### PR DESCRIPTION
**Pull request by idemiradjust**

### CODE REVIEW

**Review by rscloura — APPROVED** [review]
LGTM! 🚀

**Comment by TurKorsaN** [comment]
Hi @idemiradjust  @rscloura ,

AAR file of this version is missing in maven repo. It causes build failures for us :)

https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/

**Comment by alexvicen** [comment]
Hi @idemiradjust @rscloura I have the same error and I can't compile my app. `Could not find adjust-android-signature-3.35.1.jar`
How long will it take you to fix it?
Thank you very much

**Comment by nilsjr** [comment]
Same issue for us

_Could not find adjust-android-signature-3.35.1.aar (com.adjust.signature:adjust-android-signature:3.35.1).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.aar
         https://repo.maven.apache.org/maven2/com/adjust/signature/adjust-android-signature/3.35.1/adjust-android-signature-3.35.1.jar_

**Comment by jboteros** [comment]
@idemiradjust,   we are receiving the [same](https://github.com/adjust/adjust_signature_sdk/pull/27#issuecomment-2520509767) behaviour here, could you help us wit the fix

Thank you!

**Comment by rscloura** [comment]
Hello everyone,

Due to a network failure, version 3.35.1 Signature artifacts failed to be properly uploaded to Maven. We are currently fixing the issue, and it should be resolved very shortly. Until the issue is resolved, you may manually target a previous version, by altering the Gradle config to
```
dependencies {
    implementation('com.adjust.sdk:adjust-android:5.0.1') {
        exclude group: 'com.adjust.signature', module: 'adjust-android-signature'
    }
...
```
and explicitly adding
```
implementation 'com.adjust.signature:adjust-android-signature:3.35.0'
```

We sincerely apologise for the inconvenience, and we will let you know once the issue is resolved.

**Comment by rscloura** [comment]
Hello again. A new version (v3.35.2) has been uploaded to Maven, and should now be available normally. The issue has been resolved. Thank you for your patience, and please accept our apologies once more.

**Pull request merged**
